name: VoltskiyaComms
version: "1.0"
api-version: "1.19"
authors: [ 'Apple' ]
main: com.voltskiya.comms.VoltskiyaComms
description: a plugin for Voltskiya Communications
softdepend: [ VoltPluginManager, AppleMCUtil, DecodingNms, VoltskiyaUtilities ]
